Hotfix/refund amount
fntechgit/summit-registration pull request #60
Opened 2021-09-06 20:51 UTC by tomrndom

* Uses amounts from order on for purchased orders
* Uses calculations to show the order detail on the purchase flow

2021-09-07 13:22 UTC, smarcet commented on src/components/order-summary.js
> +              purchaseTicketTotal = purchaseTicketTotal + tixType.cost;
the ticket type cost could change on a later stage
can we use the ticket cost ?
on an ongoing purchase do you have that info ?
regards

2021-09-07 13:22 UTC, smarcet requested changes
please review comments

2021-09-08 17:04 UTC, tomrndom commented on src/components/order-summary.js
> +              purchaseTicketTotal = purchaseTicketTotal + tixType.cost;
The data is available after the reservation is made (step 3), but not on the second step.

Also the step 3 is displaying the due total incorrectly, and not showing the taxes for the order. Currently working on it

2021-09-22 22:32 UTC, smarcet commented on src/components/order-summary.js
> +                                -${reservation?.discount_amount ? reservation.discount_amount.toFixed(2) : discount_amount?.toFixed(2)}
could you merge this 2 variables on one before the return
like 
const discountAmount = reservation?.discount_amount ? reservation.discount_amount.toFixed(2) : discount_amount?.toFixed(2);

2021-09-22 22:32 UTC, smarcet commented on src/components/order-summary.js
> +                                -${reservation?.refunded_amount ? reservation.refunded_amount.toFixed(2) : refunded_amount?.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:32 UTC, smarcet commented on src/components/order-summary.js
> +                                ${reservation?.taxes_amount? reservation.taxes_amount.toFixed(2) : taxes_amount?.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:32 UTC, smarcet commented on src/components/order-summary.js
> +                                ${ order.status === 'Paid' ? '0.00' : reservation?.amount? reservation.amount.toFixed(2) : amount ? amount.toFixed(2) : purchaseTotal.toFixed(2) }
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:33 UTC, smarcet commented on src/components/order-summary.js
> +                          ${ order.status === 'Paid' ? '0.00' : reservation?.amount? reservation.amount.toFixed(2) : amount ? amount.toFixed(2) : purchaseTotal.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:33 UTC, smarcet commented on src/components/order-summary.js
> +                                ${reservation?.taxes_amount? reservation.taxes_amount.toFixed(2) : taxes_amount?.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:33 UTC, smarcet commented on src/components/order-summary.js
> +                          -${reservation?.refunded_amount ? reservation.refunded_amount.toFixed(2) : refunded_amount?.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:33 UTC, smarcet commented on src/components/order-summary.js
> +                          -${reservation?.discount_amount ? reservation.discount_amount.toFixed(2) : discount_amount?.toFixed(2)}
same as https://github.com/fntechgit/summit-registration/pull/60/files#r714355968

2021-09-22 22:34 UTC, smarcet requested changes
please review commnets

2021-09-27 17:11 UTC, smarcet approved these changes
looks good to me

2021-09-27 17:44 UTC, merged